=== Exmaralda-Org/exmaralda/src/build/misc/dtd/1.1.1/character-sets.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT character-sets (character-set+)>
<!ATTLIST character-sets name CDATA #IMPLIED>

<!ELEMENT character-set (char+)>
<!ATTLIST character-set 	name ID #REQUIRED
							extends IDREF #IMPLIED>

<!ELEMENT char (text, tooltip?)>

<!ELEMENT text (#PCDATA)>
<!ATTLIST text 	font CDATA #IMPLIED
				face CDATA #IMPLIED
				size CDATA #IMPLIED
				>
				
<!ELEMENT tooltip (#PCDATA)>
<!ATTLIST tooltip 	font CDATA #IMPLIED
					face CDATA #IMPLIED
					size CDATA #IMPLIED
					>

=== Exmaralda-Org/exmaralda/src/build/misc/dtd/1.1.1/Characters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Thomas Schmidt (UniversitÃ¤t Hamburg) -->
<!DOCTYPE character-sets SYSTEM "character-sets.dtd">
<character-sets name="Partitur-Editor-Standard">
	<character-set name="HIAT-Basic">
		<char>
			<text font="Arial Unicode MS" face="bold" size="12">((Pause))</text>
			<tooltip font="Arial Unicode MS" face="bold" size="10">HIAT Pause symbol</tooltip>
		</char>
		<char>
			<text font="Arial Unicode MS" face="bold" size="12">m&#x0301;</text>
			<tooltip font="Arial Unicode MS" face="bold" size="10">m with accute accent</tooltip>
		</char>
	</character-set>
	<character-set name="HIAT-Portuguese" extends="HIAT-Basic">
		<char>
			<text></text>
		</char>
	</character-set>
</character-sets>
